name: ilo_flutter
description: Flutter binding for Ilo Robot communication.
version: 0.0.1
homepage: https://github.com/intuition-rt/mobile-app

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.0
  universal_platform: ^1.0.0+1
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
